"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import {
  ArrowLeft,
  ArrowRight,
  Check,
  CheckCircle2,
  Copy,
  Globe,
  Loader2,
  Mic2,
  Phone,
  RefreshCw,
  Sparkles,
  Star,
} from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Switch } from "@/components/ui/switch";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { CherryVoicePicker } from "@/components/cherry-voice/voice-picker";
import { CherryVoiceWebCallDialog } from "@/components/cherry-voice/web-call-dialog";
import { VoicePicker } from "@/components/omnidim/voice-picker";
import {
  AGENT_TYPE_DESCRIPTIONS,
  AGENT_TYPE_LABELS,
  CHERRY_VOICE_INTEGRATION_TOOLS,
  type VoiceAgentType,
} from "@/lib/agent-constants";
import { api } from "@/lib/api-client";
import { cn } from "@/lib/utils";
import type { VoiceAgent } from "@/types";

type WizardStep = "type" | "voice" | "knowledge" | "website" | "integrations" | "review";

const STEP_ORDER_NATIVE: WizardStep[] = [
  "type",
  "voice",
  "knowledge",
  "website",
  "integrations",
  "review",
];

const STEP_ORDER_PLATFORM: WizardStep[] = ["type", "voice", "knowledge", "integrations", "review"];

const STEP_LABELS: Record<WizardStep, string> = {
  type: "Agent type",
  voice: "Name & voice",
  knowledge: "Knowledge base",
  website: "Website widget",
  integrations: "Integrations",
  review: "Go live",
};

type AgentWizardDialogProps = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  mode?: "create" | "edit";
  agent?: VoiceAgent | null;
  restaurantName?: string;
  onSaved?: () => void;
};

export function AgentWizardDialog({
  open,
  onOpenChange,
  mode = "create",
  agent,
  restaurantName,
  onSaved,
}: AgentWizardDialogProps) {
  const isEdit = mode === "edit" && !!agent;
  const [step, setStep] = useState<WizardStep>(isEdit ? "voice" : "type");
  const [agentType, setAgentType] = useState<VoiceAgentType>(agent?.agentType ?? "native");
  const [name, setName] = useState("Ruby");
  const [voiceId, setVoiceId] = useState("");
  const [prompt, setPrompt] = useState("");
  const [greeting, setGreeting] = useState("");
  const [widgetPosition, setWidgetPosition] = useState<"bottom-right" | "bottom-left">("bottom-right");
  const [accentColor, setAccentColor] = useState("#e11d48");
  const [widgetEnabled, setWidgetEnabled] = useState(true);
  const [busy, setBusy] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [embedScript, setEmbedScript] = useState("");
  const [demoUrl, setDemoUrl] = useState("");
  const [copied, setCopied] = useState(false);
  const [webCallOpen, setWebCallOpen] = useState(false);
  const autoGenerated = useRef(false);

  const steps = agentType === "native" ? STEP_ORDER_NATIVE : STEP_ORDER_PLATFORM;
  const stepIndex = steps.indexOf(step);
  const progress = ((stepIndex + 1) / steps.length) * 100;

  const loadPrompt = useCallback(async () => {
    setGenerating(true);
    try {
      const res = await api.post<{ prompt: string }>("/api/onboarding/agent/generate-prompt");
      setPrompt(res.prompt);
      autoGenerated.current = true;
    } catch (e) {
      toast.error((e as Error).message);
    } finally {
      setGenerating(false);
    }
  }, []);

  const loadCherryVoiceMeta = useCallback(async () => {
    try {
      const res = await api.get<{ embed_script?: string; demo_url?: string }>(
        "/api/settings/cherry-voice",
      );
      setEmbedScript(res.embed_script ?? "");
      setDemoUrl(res.demo_url ?? "");
    } catch {
      /* optional */
    }
  }, []);

  useEffect(() => {
    if (!open) {
      autoGenerated.current = false;
      setStep(isEdit ? "voice" : "type");
      return;
    }

    if (isEdit && agent) {
      setAgentType(agent.agentType);
      setName(agent.name);
      setVoiceId(agent.voice !== "Default" ? agent.voice : "");
      setGreeting(agent.greeting ?? "");
      setAccentColor(agent.accentColor ?? "#e11d48");
      setWidgetPosition(agent.widgetPosition ?? "bottom-right");
      setWidgetEnabled(agent.widgetEnabled ?? true);
      setPrompt("");
      api
        .get<{ agent?: { prompt?: string; context_breakdown?: Array<{ body?: string }> } }>(
          `/api/agents/${agent.omnidimAgentId}`,
        )
        .then((res) => {
          const p =
            res.agent?.prompt ??
            res.agent?.context_breakdown?.find((b) => b.body)?.body;
          if (p) setPrompt(p);
        })
        .catch(() => {});
      if (agent.agentType === "native") void loadCherryVoiceMeta();
      return;
    }

    setAgentType("native");
    setName("Ruby");
    setVoiceId("");
    setPrompt("");
    setGreeting(
      restaurantName
        ? `Hi! Thanks for calling ${restaurantName}. How can I help you today?`
        : "",
    );
    setAccentColor("#e11d48");
    setWidgetPosition("bottom-right");
    setWidgetEnabled(true);
    if (!autoGenerated.current) void loadPrompt();
  }, [open, isEdit, agent, loadPrompt, loadCherryVoiceMeta, restaurantName]);

  const goNext = () => {
    const idx = steps.indexOf(step);
    if (idx < steps.length - 1) setStep(steps[idx + 1]);
  };

  const goBack = () => {
    const idx = steps.indexOf(step);
    if (idx > 0) setStep(steps[idx - 1]);
  };

  const canContinue = useMemo(() => {
    if (step === "type") return true;
    if (step === "voice") return name.trim().length > 0;
    if (step === "knowledge") return !generating;
    return true;
  }, [step, name, generating]);

  const handleSave = async () => {
    if (!name.trim()) {
      toast.error("Agent name is required");
      return;
    }
    if (busy) return;

    setBusy(true);
    try {
      const payload = {
        agent_type: agentType,
        name: name.trim(),
        welcome_message:
          greeting ||
          `Thanks for calling ${restaurantName || "us"}! How can I help you today?`,
        context_breakdown: prompt
          ? [{ title: "Instructions", body: prompt, type: "text" }]
          : undefined,
        voice_id: voiceId || undefined,
        use_generated_prompt: !prompt,
        widget_position: widgetPosition,
        accent_color: accentColor,
        is_enabled: widgetEnabled,
      };

      if (isEdit && agent) {
        await api.patch(`/api/agents/${agent.omnidimAgentId}`, {
          ...payload,
          prompt: prompt || undefined,
        });
        toast.success("Agent updated");
      } else {
        const res = await api.post<{ agent_type?: string }>("/api/agents", payload);
        toast.success(
          res.agent_type === "native"
            ? "Cherry Voice agent created"
            : "Phone & Web agent created",
        );
        if (agentType === "native") await loadCherryVoiceMeta();
      }

      onSaved?.();
      onOpenChange(false);
    } catch (e) {
      toast.error((e as Error).message);
    } finally {
      setBusy(false);
    }
  };

  const copyEmbed = async () => {
    if (!embedScript) return;
    await navigator.clipboard.writeText(embedScript);
    setCopied(true);
    toast.success("Embed code copied");
    setTimeout(() => setCopied(false), 2000);
  };

  const voiceLabel = voiceId || "Sarah";

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[92vh] overflow-y-auto sm:max-w-2xl">
        <DialogHeader>
          <DialogTitle>
            {isEdit ? `Edit ${agent?.name}` : "Create voice agent"}
          </DialogTitle>
          <div className="mt-3 space-y-2">
            <div className="h-1.5 overflow-hidden rounded-full bg-muted">
              <div
                className="h-full rounded-full bg-primary transition-all"
                style={{ width: `${progress}%` }}
              />
            </div>
            <p className="text-xs font-medium text-muted-foreground">
              Step {stepIndex + 1} of {steps.length}: {STEP_LABELS[step]}
            </p>
          </div>
        </DialogHeader>

        <div className="space-y-4 py-2">
          {step === "type" && (
            <div className="grid gap-3 sm:grid-cols-2">
              {(["native", "platform"] as const).map((type) => (
                <button
                  key={type}
                  type="button"
                  onClick={() => setAgentType(type)}
                  className={cn(
                    "rounded-xl border p-4 text-left transition-colors",
                    agentType === type
                      ? "border-primary bg-primary/5 ring-1 ring-primary"
                      : "hover:bg-muted/40",
                  )}
                >
                  <div className="mb-2 flex items-center justify-between">
                    <span className="font-semibold">{AGENT_TYPE_LABELS[type]}</span>
                    {type === "native" && (
                      <Badge className="gap-1 text-[10px]">
                        <Star className="h-3 w-3" /> Recommended
                      </Badge>
                    )}
                  </div>
                  <p className="text-xs text-muted-foreground">{AGENT_TYPE_DESCRIPTIONS[type]}</p>
                  <div className="mt-3 flex items-center gap-2 text-xs text-muted-foreground">
                    {type === "native" ? (
                      <>
                        <Mic2 className="h-3.5 w-3.5" /> Website widget
                      </>
                    ) : (
                      <>
                        <Phone className="h-3.5 w-3.5" /> Phone & browser calls
                      </>
                    )}
                  </div>
                </button>
              ))}
            </div>
          )}

          {step === "voice" && (
            <div className="space-y-4">
              <div className="space-y-2">
                <Label>Agent name</Label>
                <Input value={name} onChange={(e) => setName(e.target.value)} disabled={busy} />
              </div>
              <div className="space-y-2">
                <Label>{agentType === "native" ? "Inworld voice" : "Voice"}</Label>
                {agentType === "native" ? (
                  <CherryVoicePicker value={voiceId || "Sarah"} onChange={setVoiceId} />
                ) : (
                  <VoicePicker value={voiceId} onChange={setVoiceId} autoLoad={open} />
                )}
              </div>
              {agentType === "native" && (
                <div className="space-y-2">
                  <Label>Greeting (spoken when call starts)</Label>
                  <Input
                    value={greeting}
                    onChange={(e) => setGreeting(e.target.value)}
                    placeholder={`Hi! Thanks for calling ${restaurantName || "us"}…`}
                    disabled={busy}
                  />
                </div>
              )}
            </div>
          )}

          {step === "knowledge" && (
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <Label>Agent prompt / knowledge base</Label>
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  className="h-7 gap-1 text-xs"
                  onClick={() => void loadPrompt()}
                  disabled={busy || generating}
                >
                  {generating ? (
                    <Loader2 className="h-3 w-3 animate-spin" />
                  ) : (
                    <RefreshCw className="h-3 w-3" />
                  )}
                  Regenerate
                </Button>
              </div>
              {generating && !prompt ? (
                <div className="flex items-center gap-2 rounded-lg border bg-muted/30 px-3 py-6 text-sm text-muted-foreground">
                  <Loader2 className="h-4 w-4 animate-spin" />
                  Generating prompt from your menu and profile…
                </div>
              ) : (
                <Textarea
                  rows={10}
                  className="bg-muted/40 font-mono text-xs"
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  disabled={busy}
                />
              )}
              <p className="flex items-center gap-1 text-xs text-muted-foreground">
                <Sparkles className="h-3 w-3" />
                Auto-generated from your restaurant menu and profile. Edit as needed.
              </p>
            </div>
          )}

          {step === "website" && agentType === "native" && (
            <div className="space-y-4">
              <div className="flex items-center justify-between rounded-lg border p-3">
                <div>
                  <p className="text-sm font-medium">Enable website widget</p>
                  <p className="text-xs text-muted-foreground">Show floating call button on your site</p>
                </div>
                <Switch checked={widgetEnabled} onCheckedChange={setWidgetEnabled} />
              </div>
              <div className="grid gap-4 sm:grid-cols-2">
                <div className="space-y-1.5">
                  <Label>Widget position</Label>
                  <Select
                    value={widgetPosition}
                    onValueChange={(v) => setWidgetPosition(v as "bottom-right" | "bottom-left")}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="bottom-right">Bottom right</SelectItem>
                      <SelectItem value="bottom-left">Bottom left</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-1.5">
                  <Label>Accent color</Label>
                  <Input
                    type="color"
                    value={accentColor}
                    onChange={(e) => setAccentColor(e.target.value)}
                    className="h-10 w-full cursor-pointer"
                  />
                </div>
              </div>
              <div className="space-y-2">
                <Label>Embed code</Label>
                <pre className="max-h-28 overflow-auto rounded-lg border bg-muted/40 p-3 text-xs">
                  {embedScript || "Embed code will be available after you create the agent."}
                </pre>
                {embedScript && (
                  <Button variant="outline" size="sm" className="gap-2" onClick={() => void copyEmbed()}>
                    {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                    {copied ? "Copied" : "Copy embed code"}
                  </Button>
                )}
              </div>
              <p className="text-xs text-muted-foreground">
                Advanced widget settings are also available in{" "}
                <Link href="/settings/cherry-voice" className="text-primary underline">
                  Settings → Website Voice Widget
                </Link>
                .
              </p>
            </div>
          )}

          {step === "integrations" && (
            <div className="space-y-3">
              <p className="text-sm text-muted-foreground">
                These tools are pre-connected for your restaurant. Your agent can use them during
                voice calls.
              </p>
              <ul className="grid gap-2 sm:grid-cols-2">
                {CHERRY_VOICE_INTEGRATION_TOOLS.map((tool) => (
                  <li
                    key={tool.name}
                    className="flex items-start gap-2 rounded-lg border bg-muted/20 p-3"
                  >
                    <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" />
                    <div>
                      <p className="text-sm font-medium">{tool.label}</p>
                      <p className="text-xs text-muted-foreground">{tool.description}</p>
                    </div>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {step === "review" && (
            <Card>
              <CardContent className="space-y-3 pt-6">
                <div className="flex flex-wrap items-center gap-2">
                  <Badge variant={agentType === "native" ? "default" : "secondary"}>
                    {AGENT_TYPE_LABELS[agentType]}
                  </Badge>
                  {agentType === "native" && (
                    <Badge variant={widgetEnabled ? "success" : "secondary"}>
                      Widget {widgetEnabled ? "enabled" : "disabled"}
                    </Badge>
                  )}
                </div>
                <dl className="grid gap-2 text-sm sm:grid-cols-2">
                  <div>
                    <dt className="text-muted-foreground">Name</dt>
                    <dd className="font-medium">{name}</dd>
                  </div>
                  <div>
                    <dt className="text-muted-foreground">Voice</dt>
                    <dd className="font-medium">{voiceLabel}</dd>
                  </div>
                  {agentType === "native" && greeting && (
                    <div className="sm:col-span-2">
                      <dt className="text-muted-foreground">Greeting</dt>
                      <dd className="font-medium">{greeting}</dd>
                    </div>
                  )}
                </dl>
                {agentType === "native" && (
                  <div className="flex flex-wrap gap-2">
                    {isEdit && agent && (
                      <Button
                        type="button"
                        size="sm"
                        className="gap-2"
                        onClick={() => setWebCallOpen(true)}
                      >
                        <Mic2 className="h-4 w-4" /> Web call
                      </Button>
                    )}
                    {demoUrl && (
                      <Button variant="secondary" size="sm" className="gap-2" asChild>
                        <a href={demoUrl} target="_blank" rel="noreferrer">
                          <Globe className="h-4 w-4" /> Test call page
                        </a>
                      </Button>
                    )}
                  </div>
                )}
              </CardContent>
            </Card>
          )}
        </div>

        <DialogFooter className="flex-col gap-2 sm:flex-row sm:justify-between">
          <div className="flex gap-2">
            {stepIndex > 0 && !(isEdit && step === "voice") && (
              <Button variant="outline" onClick={goBack} disabled={busy}>
                <ArrowLeft className="mr-1 h-4 w-4" /> Back
              </Button>
            )}
          </div>
          <div className="flex gap-2">
            <Button variant="outline" onClick={() => onOpenChange(false)} disabled={busy}>
              Cancel
            </Button>
            {step !== "review" ? (
              <Button onClick={goNext} disabled={!canContinue || busy}>
                Continue <ArrowRight className="ml-1 h-4 w-4" />
              </Button>
            ) : (
              <Button onClick={() => void handleSave()} disabled={busy || generating}>
                {busy ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}
                {isEdit ? "Save changes" : "Create agent"}
              </Button>
            )}
          </div>
        </DialogFooter>
      </DialogContent>

      {isEdit && agentType === "native" && agent && (
        <CherryVoiceWebCallDialog
          open={webCallOpen}
          onOpenChange={setWebCallOpen}
          agentId={agent.omnidimAgentId}
          agentName={agent.name}
        />
      )}
    </Dialog>
  );
}
