"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { Loader2, RefreshCw, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { VoicePicker } from "@/components/omnidim/voice-picker";
import { api } from "@/lib/api-client";
import type { VoiceAgent } from "@/types";

type AgentFormDialogProps = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  mode: "create" | "edit";
  agent?: VoiceAgent | null;
  restaurantName?: string;
  onSaved?: () => void;
};

export function AgentFormDialog({
  open,
  onOpenChange,
  mode,
  agent,
  restaurantName,
  onSaved,
}: AgentFormDialogProps) {
  const [name, setName] = useState("");
  const [prompt, setPrompt] = useState("");
  const [voiceId, setVoiceId] = useState("");
  const [busy, setBusy] = useState(false);
  const [generating, setGenerating] = useState(false);
  const autoGenerated = useRef(false);

  const loadPrompt = useCallback(async () => {
    setGenerating(true);
    try {
      const res = await api.post<{ prompt: string }>("/api/onboarding/agent/generate-prompt");
      setPrompt(res.prompt);
      autoGenerated.current = true;
    } catch (e) {
      toast.error((e as Error).message);
    } finally {
      setGenerating(false);
    }
  }, []);

  useEffect(() => {
    if (!open) {
      autoGenerated.current = false;
      return;
    }

    if (mode === "edit" && agent) {
      setName(agent.name);
      setVoiceId(agent.voice !== "Default" ? agent.voice : "");
      setPrompt("");
      api
        .get<{ agent?: { context_breakdown?: Array<{ body?: string }> } }>(
          `/api/agents/${agent.omnidimAgentId}`,
        )
        .then((res) => {
          const breakdown = res.agent?.context_breakdown;
          const instructions = breakdown?.find((b) => b.body)?.body;
          if (instructions) setPrompt(instructions);
        })
        .catch(() => {});
      return;
    }

    setName("Ruby");
    setVoiceId("");
    setPrompt("");
    if (!autoGenerated.current) {
      void loadPrompt();
    }
  }, [open, mode, agent, loadPrompt]);

  const handleSave = async () => {
    if (!name.trim()) {
      toast.error("Agent name is required");
      return;
    }
    if (busy) return;

    setBusy(true);
    try {
      if (mode === "create") {
        await api.post("/api/agents", {
          name: name.trim(),
          welcome_message: `Thanks for calling ${restaurantName || "us"}! How can I help you today?`,
          context_breakdown: prompt
            ? [{ title: "Instructions", body: prompt, type: "text" }]
            : undefined,
          voice_id: voiceId || undefined,
          use_generated_prompt: !prompt,
        });
        toast.success("Agent created");
      } else if (agent) {
        await api.patch(`/api/agents/${agent.omnidimAgentId}`, {
          name: name.trim(),
          prompt: prompt || undefined,
          voice_id: voiceId || undefined,
        });
        toast.success("Agent updated");
      }
      onSaved?.();
      onOpenChange(false);
    } catch (e) {
      toast.error((e as Error).message);
    } finally {
      setBusy(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-lg">
        <DialogHeader>
          <DialogTitle>{mode === "create" ? "New voice agent" : "Edit agent"}</DialogTitle>
        </DialogHeader>
        <div className="space-y-4">
          <div className="space-y-2">
            <Label>Agent name</Label>
            <Input value={name} onChange={(e) => setName(e.target.value)} disabled={busy} />
          </div>
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label>Agent prompt</Label>
              <Button
                type="button"
                variant="ghost"
                size="sm"
                className="h-7 gap-1 text-xs"
                onClick={() => void loadPrompt()}
                disabled={busy || generating}
              >
                {generating ? (
                  <Loader2 className="h-3 w-3 animate-spin" />
                ) : (
                  <RefreshCw className="h-3 w-3" />
                )}
                Regenerate
              </Button>
            </div>
            {generating && !prompt ? (
              <div className="flex items-center gap-2 rounded-lg border bg-muted/30 px-3 py-6 text-sm text-muted-foreground">
                <Loader2 className="h-4 w-4 animate-spin" />
                Generating prompt from your menu and profile…
              </div>
            ) : (
              <Textarea
                rows={8}
                className="bg-muted/40 font-mono text-xs"
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                disabled={busy}
              />
            )}
            {mode === "create" && prompt && !generating && (
              <p className="flex items-center gap-1 text-xs text-muted-foreground">
                <Sparkles className="h-3 w-3" /> Auto-filled from your restaurant data. Edit as needed.
              </p>
            )}
          </div>
          <div className="space-y-2">
            <Label>Voice</Label>
            <VoicePicker value={voiceId} onChange={setVoiceId} autoLoad={open} />
          </div>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)} disabled={busy}>
            Cancel
          </Button>
          <Button onClick={() => void handleSave()} disabled={busy || generating}>
            {busy ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}
            {mode === "create" ? "Create agent" : "Save changes"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
